version: '2'
services:
  hello1:
    build: ./hello
    image: go-hello1
    ports:
      - 8001:8000
  hello2:
    build: ./hello
    image: go-hello2
    ports:
      - 8002:8000
  nginx:
    image: nginx
    ports:
      - 8000:80
      - 18000:18080
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"